/**
 * Utilities for handling user entities across both anonymous (Cyrnea) and Supabase (Inseme) contexts
 *
 * =========================================================================================
 * 🛡️ INSEME USER TYPES & AUTHENTICATION STRATEGY
 * =========================================================================================
 * The system handles three distinct levels of user identity.
 * PLEASE READ THIS before modifying authentication logic.
 *
 * 1. TYPE 1: LOCAL VISITOR (The "Cyrnea" User)
 *    - Identity: Purely local, generated via crypto.randomUUID().
 *    - Storage: localStorage ('cyrnea_anon_id').
 *    - Supabase: DOES NOT EXIST in auth.users.
 *    - Auth State: null (unauthenticated).
 *    - Capabilities: Read-only or local-only interactions.
 *    - Recognition: user.isAnonymous === true && !isValidSupabaseUserId(user.id)
 *
 * 2. TYPE 2: GUEST USER (The "Inseme" Participant)
 *    - Identity: Generated by Supabase Auth (Anonymous Sign-In).
 *    - Storage: Supabase Session Token (cookie/localStorage).
 *    - Supabase: EXISTS in auth.users with is_anonymous: true.
 *    - Auth State: authenticated (as anonymous).
 *    - Capabilities: Can interact with RLS-protected resources.
 *    - Recognition: user.is_anonymous === true && isValidSupabaseUserId(user.id)
 *
 * 3. TYPE 3: AUTHENTICATED USER (The "Platform" Member)
 *    - Identity: Email/Password, Social Login, etc.
 *    - Storage: Supabase Session Token.
 *    - Supabase: EXISTS in auth.users and public.users.
 *    - Auth State: fully authenticated.
 *    - Capabilities: Full persistence, cross-device login.
 *    - Recognition: user.is_anonymous === false
 * =========================================================================================
 */

/**
 * Check if a user ID is an anonymous user ID (Legacy "anon_" format)
 * Note: Modern anonymous users (Type 1 & 2) may use standard UUIDs.
 * ALWAYS check user.isAnonymous flag in addition to ID format.
 *
 * @param {string} userId - The user ID to check
 * @returns {boolean} True if the ID is an anonymous user ID
 */
export function isAnonymousUserId(userId) {
  if (!userId || typeof userId !== "string") return false;
  return userId.startsWith("anon_");
}

/**
 * Validate if a user ID can be used to query the Supabase users table
 * @param {string} userId - The user ID to validate
 * @returns {boolean} True if the ID is a valid Supabase UUID
 */
export function isValidSupabaseUserId(userId) {
  if (!userId || typeof userId !== "string") return false;

  // Anonymous IDs (Type 1 Legacy) should not query Supabase
  if (isAnonymousUserId(userId)) return false;

  // Basic UUID validation (Supabase uses UUIDs)
  const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
  return uuidRegex.test(userId);
}

/**
 * Get a unified user object that works for all user types (Type 1, 2, and 3)
 * @param {Object} user - User object from any source
 * @returns {Object} Unified user object
 */
export function normalizeUserObject(user) {
  if (!user) return null;

  // If it's already marked as anonymous (Type 1 or Type 2)
  if (user.is_anonymous || user.isAnonymous || isAnonymousUserId(user.id)) {
    return {
      id: user.id,
      display_name: user.display_name || user.pseudo || "Anonyme",
      is_anonymous: true,
      isAnonymous: true, // Frontend compatibility
      metadata: {
        avatarUrl:
          user.metadata?.avatarUrl ||
          `https://api.dicebear.com/7.x/notionists/svg?seed=${user.id}&backgroundColor=transparent`,
        ...user.metadata,
      },
      ...user,
    };
  }

  // For Supabase users (Type 3), ensure consistent structure
  return {
    id: user.id,
    display_name: user.display_name || user.email?.split("@")[0] || "Utilisateur",
    is_anonymous: false,
    isAnonymous: false,
    metadata: {
      avatarUrl: user.metadata?.avatarUrl,
      ...user.metadata,
    },
    ...user,
  };
}

/**
 * Create a default anonymous user object for a given ID (Type 1 legacy)
 * @param {string} userId - The anonymous user ID
 * @returns {Object} A default anonymous user object
 */
export function createAnonymousUserObject(userId) {
  return {
    id: userId,
    display_name: "Anonyme",
    pseudo: "Anonyme",
    is_anonymous: true,
    isAnonymous: true,
    metadata: {
      avatarUrl: `https://api.dicebear.com/7.x/notionists/svg?seed=${userId}&backgroundColor=transparent`,
    },
  };
}
