import test from "node:test";
import assert from "node:assert/strict";
import {LocalGovernedEffectGateway} from "./local-governed-effect-gateway.js";
const setup=()=>{const g=new LocalGovernedEffectGateway({now:()=>100});g.seed("p",{holder:"B",epoch:2,mandateRevision:7,expiresAt:200,value:"initial"});return g};
test("current version but stale holder rejected",()=>{const g=setup(),v=g.inspect("p").version;assert.equal(g.commit({packetRef:"p",holder:"A",epoch:1,mandateRevision:7,expectedVersion:v,idempotencyKey:"a",value:"bad"}).code,"AUTHORITY_REJECTED");assert.equal(g.inspect("p").value,"initial")});
test("valid holder commits, retry idempotent, conflicting replay rejected",()=>{const g=setup(),req={packetRef:"p",holder:"B",epoch:2,mandateRevision:7,expectedVersion:1,idempotencyKey:"b",value:"good"};assert.equal(g.commit(req).code,"COMMITTED");assert.equal(g.commit(req).code,"ALREADY_APPLIED");assert.equal(g.commit({...req,value:"different"}).code,"IDEMPOTENCY_CONFLICT");assert.equal(g.inspect("p").value,"good")});
test("revocation rejects current-version holder",()=>{const g=setup();g.revoke("p");const version=g.inspect("p").version;assert.equal(g.commit({packetRef:"p",holder:"B",epoch:2,mandateRevision:7,expectedVersion:version,idempotencyKey:"revoked",value:"bad"}).code,"AUTHORITY_REJECTED")});
test("takeover rejects A even with fresh version",()=>{const g=setup();g.transfer("p",{holder:"C",epoch:3,mandateRevision:8,expiresAt:250});const version=g.inspect("p").version;assert.equal(g.commit({packetRef:"p",holder:"B",epoch:2,mandateRevision:7,expectedVersion:version,idempotencyKey:"stale",value:"bad"}).code,"AUTHORITY_REJECTED");assert.equal(g.commit({packetRef:"p",holder:"C",epoch:3,mandateRevision:8,expectedVersion:version,idempotencyKey:"new",value:"ok"}).code,"COMMITTED")});
test("expired lease rejected",()=>{const g=new LocalGovernedEffectGateway({now:()=>201});g.seed("p",{holder:"B",epoch:2,mandateRevision:7,expiresAt:200,value:"initial"});assert.equal(g.commit({packetRef:"p",holder:"B",epoch:2,mandateRevision:7,expectedVersion:1,idempotencyKey:"late",value:"bad"}).code,"AUTHORITY_REJECTED")});
